[project]
name = "switch-auto-play"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "thr3a", email = "thr3a@example.com" }
]
requires-python = ">=3.11"
dependencies = [
    "nxbt>=0.1.4",
    "opencv-python>=5.0.0.93",
    "ruff>=0.16.8",
]

[project.scripts]
switch-auto-play = "switch_auto_play:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
